<label name="email">Email</label>
<input type="email" value="example@example.com"/><br>
<label name="name">Name</label>
<input type="name"/><br>
<label name="lastname">Lastname</label>
<input type="lastname"/><br>
<label name="password">Password</label>
<input type="password"/><br>
<label name="cpassword">Confirm Password</label>
<input type="cpassword"/><br>
<input type="submit" value="Confirm Registration"/>

